template = "https://github.com/giellalt/template-lang-und"
rev_id = 331
template_sha = "8cacf2c4546a4e46881bd306e8c347aa8b1ae938"

[replacements]
__GLOTTOLOG_ID__ = "turk1308"
__REPO__ = "lang-tuv"
__UND2C__ = "tuv"
__UNDEFINED__ = "Turkana"
__UND__ = "tuv"
