template = "https://github.com/giellalt/template-lang-und"
rev_id = 294
template_sha = "a620868b33dee503846060f7bd6c6e88f3c1f6d1"

[replacements]
__GLOTTOLOG_ID__ = "turk1308"
__REPO__ = "lang-tuv"
__UND2C__ = "tuv"
__UNDEFINED__ = "Turkana"
__UND__ = "tuv"
