template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "c0f15a905d69cb451762275644bf5c3133bfc106"

[replacements]
__GLOTTOLOG_ID__ = "turk1308"
__REPO__ = "lang-tuv"
__UND2C__ = "tuv"
__UNDEFINED__ = "Turkana"
__UND__ = "tuv"
